### ISSUE TITLE
implements other load balance strategy?

### ISSUE THREAD

**Issue by brownchow** [voldyman/GoLoadBalance#2]
in github topic https://github.com/topics/load-balancer, there are many load balance implementation

this project seems only implemet round robin strategy. there are many other strategies,
such as weight, ip_hash, fair, url_hash..... maybe we can implement these strategies

**Comment by voldyman** [comment]
Other load load balancing strategies could be implemented but let me provide some history of this project.

I created this in college, in feb 2015 because my college had blocked access to websites like reddit, facebook, etc. the goal was to bypass the restrictions while being able to provide a seemless experience.

I had a few VPSs, one from digital ocean that i paid for, one on insomnia247.nl graciously given for free by [coolfire](https://git.insomnia247.nl/users/coolfire/), and one more from [respiratio](http://respiratio.net/) provided for free by @nohitall.

This project allowed me to create ssh reverse proxy connections to all these servers and update my system settings to connect to just one local proxy address.

In 2015, i had been writing Go for a while but wasn't sure if i could build something like this which would also be reliable. So i built the simplest possible working program. I had plans of adding different strategies for balancing, detecting which backend is slow and de-prioritizing the routing to that backend.

But, it turned out that the performance of the naive implementation was so good that i didn't even notice there was a proxy running. One optimization my local copy had that this version doesn't have is the ability to spawn new backend connections since I could only multiplex so many connections over one ssh connection. Http 1.x is short enough that it usually didn't matter.

This project lives here as an artifact of what Go let me built with minimal experience, I probably won't be contributing or actively maintaining it since i don't have the need to load balance or proxy connections.

Today there are much better alternatives available that didn't exist then, (traefik was created 7 months after i built this, for example)
